version: '2'
services: 
  php-apache:
    build:
      context: .
    image: registry.diginfra.net/retrolamp-php-apache
    ports:
      - 8089:80
    volumes: 
      - $LOCAL_WEBROOT:/var/www/html
    environment:
      TITLE: "OLD LAMPIE"
      TZ: "Europe/Amsterdam"
      ADMINER_DEFAULT_SERVER: host.docker.internal

#  mariadb:
#    image: mariadb:5.5
#    volumes:
#       - mariavol:/var/lib/mysql
#    environment:
#      TZ: "Europe/Amsterdam"
#      MYSQL_ROOT_PASSWORD: "rood"
#      MYSQL_DATABASE: "opvang"
#
#volumes:
#  mariavol:
